AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Deploy DigiPassApi Inventory Keeper Lambda


Resources:
  LambdaIAMRole:
    Type: AWS::IAM::Role
    Properties:
      Description: " Lambda execution role"
      RoleName: "InventoryKeeperLambdaExecutionRole"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - sts:AssumeRole
            Principal:
              Service: "lambda.amazonaws.com"
            Effect: Allow
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole #Permission to upload logs to CloudWatch
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite 
        - arn:aws:iam::aws:policy/AmazonSQSFullAccess
      Policies:
      - PolicyName: cloudwatchPutMetricData
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - cloudwatch:PutMetricData
            Resource: '*'
            
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: "Inventory Keeper Lambda"
      FunctionName: InventoryKeeper
      Handler: bootstrap
      Runtime: provided.al2
      MemorySize: 128
      Architectures:
      - arm64
      Timeout: 30
      CodeUri: "../../digi-pass-inventory-keeper/target/lambda/digi-pass-inventory-keeper/"
      Role: !GetAtt LambdaIAMRole.Arn
      Policies:
      - AWSLambda_FullAccess
      Environment:
        Variables:
          MongoDbConfig__Database: DigiPassDb
          RUST_LOG: "debug"
      Events:
        Scheduled:
          Type: Schedule
          Properties:
            Schedule: 'cron(0 0 * * ? *)'
            Name: HalfHour
            Description: HalfHour
            Enabled: false

