AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Deploy DigiPassApi Lambda
Parameters:
  EventBusName: #Name of the Lambda Module
    Description: The name of the EventBusName
    Type: String
    Default: "aws.partner/mongodb.com/stitch.trigger/65ec194a713e980c34e036ca"



Resources:
  LambdaIAMRole:
    Type: AWS::IAM::Role
    Properties:
      Description: " Lambda execution role"
      RoleName: "LambdaExecutionRole"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - sts:AssumeRole
            Principal:
              Service: "lambda.amazonaws.com"
            Effect: Allow
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole #Permission to upload logs to CloudWatch
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite 
      Policies:
      - PolicyName: cloudwatchPutMetricData
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - cloudwatch:PutMetricData
            Resource: '*'
            
  

  GenerateInventoryQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: GenerateInventoryQueue

  GenerateInventoryQueueRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: Default Event Rule
      EventBusName: !Ref PartnerEventSource
      EventPattern: 
        source: 
        - prefix: "aws.partner/mongodb.com"
        detail:
          operationType: 
          - "insert"
          ns:
            coll: 
            - "GenerateInventories"
          fullDocument:
            status:
            - "Pending"
      Name: default-rule
      State: ENABLED
      Targets:
       - 
         Arn: 
           Fn::GetAtt:
             - "GenerateInventoryQueue"
             - "Arn"
         Id: "GenerateInventoryQueue"

  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: "Generate Inventory Lambda"
      FunctionName: GenerateInventory
      Handler: bootstrap
      Runtime: provided.al2
      MemorySize: 128
      Architectures:
      - arm64
      Timeout: 30
      CodeUri: "../../generate-inventory-handler/target/lambda/generate-inventory-handler/"
      Role: !GetAtt LambdaIAMRole.Arn
      Policies:
      - AWSLambda_FullAccess
      Environment:
        Variables:
          MongoDbConfig__Database: DigiPass
          JwtConfig__Issuer: https://dev-8cvq4bjo02vym8zq.us.auth0.com/
          JwtConfig__Audience: http://localhost:3000/
          RUST_LOG: "info,digi_pass=debug"
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !Ref GenerateInventoryQueue
            BatchSize: 10
            RestApiId: !Ref PartnerEventSource