AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Digi Pass event bus using EventBridge Lambda and MongoDB Atlas
Parameters:
  PartnerEventSource:
    Description: Name of Partner Event Source
    Type: String
    Default: 'aws.partner/mongodb.com/stitch.trigger/65ec194a713e980c34e036ca'
  

Resources:
  PartnerEventBus: 
    Type: AWS::Events::EventBus
    Properties: 
      EventSourceName: !Ref PartnerEventSource
      Name: !Ref PartnerEventSource
