
# @name login
POST https://dev-8cvq4bjo02vym8zq.us.auth0.com/oauth/token
Content-Type: application/json

{"client_id":"{{client_id}}",
"client_secret":"{{client_secret}}",
"audience":"{{audience}}",
"grant_type":"client_credentials"}


###  
# @name create_event
POST {{baseUrl}}/events
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name" : "Test Event 2323",
    "price" : 25000,
    "start_sale_date_time": "2024-03-23T18:25:43.511Z",
    "end_sale_date_time": "2024-04-23T18:25:43.511Z",
    "start_date_time": "2024-04-22T18:25:43.511Z",
    "end_date_time": "2024-04-23T18:25:43.511Z"
}



#######################################
#Invalid request
POST {{baseUrl}}/events
Content-Type: application/json

{
    "name" : "",
    "start_sale_date_time": "2024-05-23T18:25:43.511Z",
    "end_sale_date_time": "2024-04-23T18:25:43.511Z",
    "start_date_time": "2024-05-23T18:25:43.511Z",
    "end_date_time": "2024-04-23T18:25:43.511Z"
}

#########################################

@authToken = {{login.response.body.$.access_token}}
@event_id = {{create_event.response.body.$.id}}


# @name GetEvents
GET {{baseUrl}}/events
Authorization: Bearer {{authToken}}
x-api-key: eMmTHHarRlwJs5BOrUcy6YyumhsFvZZ2fTO7WnE6

###
POST {{baseUrl}}/inventories/generate
Authorization: Bearer {{authToken}}
Content-Type: application/json
x-api-key: {{api_key}}

{
    "event_id" : "65e570869825fdfdf094d34d",
    "number_to_create": 3434
}

###
POST {{baseUrl}}/inventories/batch
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "event_id" : "{{event_id}}",
    "quantity" : 1000
}


###
POST {{baseUrl}}/inventories/reserve
Authorization: Bearer {{authToken}}
Content-Type: application/json
x-api-key: {{api_key}}

{
    "event_id" : "65f7220e9055c6f3d22ab77f",
    "quantity" : 5
}


### 
# @name CreateBasket
POST {{baseUrl}}/baskets
Authorization: Bearer {{authToken}}
Content-Type: application/json
x-api-key: {{api_key}}

{
    "add_basket_item_request" : [
        {
            "event_id" : "66026740faddba649fd81f89",
            "quantity": 5
        }
    ]
}

###
POST {{baseUrl}}/payments/checkout
Authorization: Bearer {{authToken}}
Content-Type: application/json
x-api-key: {{api_key}}

{
    "basket_id" : "{{CreateBasket.response.body.$.basket_id}}"
}

###
POST {{baseUrl}}/payments/checkout/paymongo
Content-Type: application/json
Paymongo-Signature: t=1711534472,te=5cb40280497c469fdce46430c867f7d8e62193c7389f9098a6e3c813bdadf4ed,li=

{
    "data": {
        "id": "evt_JPBqtWR2wY7ppsj3HeR9Tznq",
        "type": "event",
        "attributes": {
            "type": "checkout_session.payment.paid",
            "livemode": false,
            "data": {
                "id": "cs_7yMM5J5tVFTRnpGG1EoDGtBh",
                "type": "checkout_session",
                "attributes": {
                    "billing": {
                        "address": {
                            "city": null,
                            "country": null,
                            "line1": null,
                            "line2": null,
                            "postal_code": null,
                            "state": null
                        },
                        "email": null,
                        "name": null,
                        "phone": null
                    },
                    "billing_information_fields_editable": "enabled",
                    "cancel_url": null,
                    "checkout_url": "https://checkout.paymongo.com/cs_qzAtJyH1tHtKUYJ8LYv3Qym9_client_T5guKbw4jwwA43Q27HxamLEo#cGtfdGVzdF9YVjZiQUZmcEo1VWVpY25DRHd6VVFuOGE=",
                    "client_key": "cs_qzAtJyH1tHtKUYJ8LYv3Qym9_client_T5guKbw4jwwA43Q27HxamLEo",
                    "customer_email": null,
                    "description": "Pass",
                    "line_items": [
                        {
                            "amount": 25000,
                            "currency": "PHP",
                            "description": "Test Event 2323",
                            "images": [],
                            "name": "Test Event 2323",
                            "quantity": 5
                        }
                    ],
                    "livemode": false,
                    "merchant": "Vicente Test Business",
                    "paid_at": 1711534419,
                    "payments": [
                        {
                            "id": "pay_hmoytgoh7pQ4zjgyck6LPgfc",
                            "type": "payment",
                            "attributes": {
                                "access_url": null,
                                "amount": 125000,
                                "balance_transaction_id": "bal_txn_bPZw6sgwdfPPhLDqma9sYDXw",
                                "billing": {
                                    "address": {
                                        "city": "",
                                        "country": "",
                                        "line1": "",
                                        "line2": "",
                                        "postal_code": "",
                                        "state": ""
                                    },
                                    "email": "v.g.albonian.dev@gmail.com",
                                    "name": "kjhkj",
                                    "phone": "9382271979"
                                },
                                "currency": "PHP",
                                "description": "Pass",
                                "disputed": false,
                                "external_reference_number": null,
                                "fee": 3125,
                                "instant_settlement": null,
                                "livemode": false,
                                "net_amount": 121875,
                                "origin": "api",
                                "payment_intent_id": "pi_pqLZdR42W5Xa4GgA1wVQwZ4b",
                                "payout": null,
                                "source": {
                                    "id": "src_Trcpwa2nkexiudQ2g3ud3xVG",
                                    "type": "gcash"
                                },
                                "statement_descriptor": "Vicente Test Business",
                                "status": "paid",
                                "tax_amount": null,
                                "metadata": null,
                                "refunds": [],
                                "taxes": [],
                                "available_at": 1712134800,
                                "created_at": 1711534419,
                                "credited_at": 1712739600,
                                "paid_at": 1711534419,
                                "updated_at": 1711534419
                            }
                        }
                    ],
                    "payment_intent": {
                        "id": "pi_pqLZdR42W5Xa4GgA1wVQwZ4b",
                        "type": "payment_intent",
                        "attributes": {
                            "amount": 125000,
                            "capture_type": "automatic",
                            "client_key": "pi_pqLZdR42W5Xa4GgA1wVQwZ4b_client_3neDA1AFQTWNmaKMxkXfCWuz",
                            "currency": "PHP",
                            "description": "Pass",
                            "livemode": false,
                            "statement_descriptor": "Vicente Test Business",
                            "status": "succeeded",
                            "last_payment_error": null,
                            "payment_method_allowed": [
                                "grab_pay",
                                "paymaya",
                                "card",
                                "gcash"
                            ],
                            "payments": [
                                {
                                    "id": "pay_hmoytgoh7pQ4zjgyck6LPgfc",
                                    "type": "payment",
                                    "attributes": {
                                        "access_url": null,
                                        "amount": 125000,
                                        "balance_transaction_id": "bal_txn_bPZw6sgwdfPPhLDqma9sYDXw",
                                        "billing": {
                                            "address": {
                                                "city": "",
                                                "country": "",
                                                "line1": "",
                                                "line2": "",
                                                "postal_code": "",
                                                "state": ""
                                            },
                                            "email": "v.g.albonian.dev@gmail.com",
                                            "name": "kjhkj",
                                            "phone": "9382271979"
                                        },
                                        "currency": "PHP",
                                        "description": "Pass",
                                        "disputed": false,
                                        "external_reference_number": null,
                                        "fee": 3125,
                                        "instant_settlement": null,
                                        "livemode": false,
                                        "net_amount": 121875,
                                        "origin": "api",
                                        "payment_intent_id": "pi_pqLZdR42W5Xa4GgA1wVQwZ4b",
                                        "payout": null,
                                        "source": {
                                            "id": "src_Trcpwa2nkexiudQ2g3ud3xVG",
                                            "type": "gcash"
                                        },
                                        "statement_descriptor": "Vicente Test Business",
                                        "status": "paid",
                                        "tax_amount": null,
                                        "metadata": null,
                                        "refunds": [],
                                        "taxes": [],
                                        "available_at": 1712134800,
                                        "created_at": 1711534419,
                                        "credited_at": 1712739600,
                                        "paid_at": 1711534419,
                                        "updated_at": 1711534419
                                    }
                                }
                            ],
                            "next_action": null,
                            "payment_method_options": {
                                "card": {
                                    "request_three_d_secure": "any"
                                }
                            },
                            "metadata": null,
                            "setup_future_usage": null,
                            "created_at": 1711534381,
                            "updated_at": 1711534420
                        }
                    },
                    "payment_method_types": [
                        "card",
                        "grab_pay",
                        "gcash",
                        "paymaya"
                    ],
                    "payment_method_used": "gcash",
                    "reference_number": null,
                    "send_email_receipt": false,
                    "show_description": false,
                    "show_line_items": true,
                    "status": "active",
                    "success_url": null,
                    "created_at": 1711534381,
                    "updated_at": 1711534381,
                    "metadata": null
                }
            },
            "previous_data": {},
            "created_at": 1711534420,
            "updated_at": 1711534420
        }
    }
}