
# @name login
POST https://dev-8cvq4bjo02vym8zq.us.auth0.com/oauth/token
Content-Type: application/json

{"client_id":"{{client_id}}",
"client_secret":"{{client_secret}}",
"audience":"{{audience}}",
"grant_type":"client_credentials"}


###  
# @name create_event
POST {{baseUrl}}/events
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name" : "Test Event 2323",
    "price" : 25000,
    "start_sale_date_time": "2024-03-23T18:25:43.511Z",
    "end_sale_date_time": "2024-04-23T18:25:43.511Z",
    "start_date_time": "2024-04-22T18:25:43.511Z",
    "end_date_time": "2024-04-23T18:25:43.511Z"
}



#######################################
#Invalid request
POST {{baseUrl}}/events
Content-Type: application/json

{
    "name" : "",
    "start_sale_date_time": "2024-05-23T18:25:43.511Z",
    "end_sale_date_time": "2024-04-23T18:25:43.511Z",
    "start_date_time": "2024-05-23T18:25:43.511Z",
    "end_date_time": "2024-04-23T18:25:43.511Z"
}

#########################################

@authToken = {{login.response.body.$.access_token}}
@event_id = {{create_event.response.body.$.id}}


# @name GetEvents
GET {{baseUrl}}/events
Authorization: Bearer {{authToken}}
x-api-key: eMmTHHarRlwJs5BOrUcy6YyumhsFvZZ2fTO7WnE6

###
POST {{baseUrl}}/inventories/generate
Authorization: Bearer {{authToken}}
Content-Type: application/json
x-api-key: {{api_key}}

{
    "event_id" : "65e570869825fdfdf094d34d",
    "number_to_create": 3434
}

###
POST {{baseUrl}}/inventories/batch
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "event_id" : "{{event_id}}",
    "quantity" : 1000
}


###
POST {{baseUrl}}/inventories/reserve
Authorization: Bearer {{authToken}}
Content-Type: application/json
x-api-key: {{api_key}}

{
    "event_id" : "65f7220e9055c6f3d22ab77f",
    "quantity" : 5
}


###
POST {{baseUrl}}/basket
Authorization: Bearer {{authToken}}
Content-Type: application/json
x-api-key: {{api_key}}

{
    "add_basket_item_request" : [
        {
            "event_id" : "{{event_id}}",
            "quantity": 5
        }
    ]
}