name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    defaults:
      run:
        working-directory: ./digi-pass
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
    - name: Install Zig toolchain
      uses: korandoru/setup-zig@v1
      with:
        zig-version: 0.10.0
    - name: Install Cargo Lambda
      uses: jaxxstorm/action-install-gh-release@v1.9.0
      with:
        repo: cargo-lambda/cargo-lambda
        platform: linux # Other valid options: 'windows' or 'darwin'
        arch: x86_64  # Other valid options for linux: 'aarch64'
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: build lambda
      run: cargo lambda build --release
    # Add your build steps below
