name: Deploy event bus

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    defaults:
      run:
        working-directory: ./aws/generate-inventory-handler/
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure AWS credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.REGION }}
    - uses: actions/download-artifact@v4.1.4
      with: 
        path: ./generate-inventory-handler/target/
    - name: Deploy lambda
      run: |
          tree
          aws cloudformation update-stack --stack-name digi-pass-event-bus --template-body file://template.yml --capabilities CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM CAPABILITY_IAM
